### ISSUE TITLE
Linux and internal limits

### ISSUE THREAD

**Issue by aksr** [phonologus/edam#1]
I'm  a big fan of _sam language_: easy to learn, intuitive, minimalistic, composable and, in general, very powerful.  I use it (almost) daily.
With speed, efficiency and easiness, making changes on hundreds of files with _any other tool_ isn't even close.

I tried `edam`, and I encountered a few problems, e.g., size of line limit.

As Pike said in `The Text Editor sam`, 

> its lack of internal limits and sizes is a virtue.  Because it avoids
> all fixed-size tables and data structures, sam is able to make global
> changes to files that some of our other tools cannot even read.

And the current p9p's version does have all internal limits removed 
(size of line, max number of files opened etc.)

With more love, this tool could be a useful addition to *nix toolbox.
Why not make it usable on linux, remove number-of-files-open limit, string limit etc.?

What do you think?

**Comment by phonologus** [comment]
I agree. I'm happy to see what I can do.

**Comment by phonologus** [comment]
Update:  the Research Unix Version 10 sam that edam is based off doesn't have any internal limits that I can see (it uses heap allocation more or less everywhere that Plan9 sam does). As you rightly point out, that was one of Rob Pike's aims for sam from the very beginning. I have just tried opening and manipulating files with 50,000 character lines with no problems on a MacOS build of edam, but I'm getting a core dump on a Linux build, so I believe the problem is with MacOS vs. Linux, and/or clang vs. gcc. Hopefully when I nail down where the incompatibility is, it will resolve all the unexpected limits you were hitting on Linux.

**Comment by phonologus** [comment]
OK, so I built a macOS binary with `gcc`, and it crashed exactly as the Linux+`gcc` binary did, so the problem is definitely `gcc` vs `clang` rather than Mac vs Linux or Plan9 vs Unix. I'll continue looking for the bug, but in the meantime, the workaround is to build with `clang`.

**Comment by phonologus** [comment]
I've pushed the fix, so it should all be working now with either `gcc` or `clang`
