### ISSUE TITLE
Segmentation fault: undo

### ISSUE THREAD

**Issue by aksr** [phonologus/edam#2]
Have some fairly large file, execute, for example, `,x/a/c/A/`, then `u` (undo) → segfault.
Segfaults after a large number of modifications (I think).

**Comment by phonologus** [comment]
The fix for the `gcc` vs `clang` weirdness (Issue #1) was in the code for processing the transcript file(s), which makes some dangerous/ugly assumptions about integer serialization, so it does not surprise me that `u` falls over (`u` relies on reading back the transcript file). I suspect the fix will be to write a proper pair of serialization/deserialization functions to replace the nasty GETT() / PUTT() macros. I'll work on the fix this evening (GMT).

**Comment by phonologus** [comment]
Found the bug. Not as drastic as I had thought. A call to `memmove()` was being made with the wrong byte count. I'm about to push the fix.
